### ISSUE TITLE
Syntax highlighting broken for inline comments

### ISSUE THREAD

**Issue by pchaigno** [opal/opal.tmbundle#1]
It looks like inline comments with `--` are not highlighted properly: https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fopal%2Fopal.tmbundle%2Fmaster%2FSyntaxes%2FOpal.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fpchaigno%2Flinguist%2Fmaster%2Fsamples%2FOpal%2FDeepakChopra.opal&code=

**Comment by elia** [comment]
> This is not the Opal you're looking for

The Opal we refer to in this bundle is a ruby to javascript compiler, the language grammar in this repo adds support for highlighting js embedded into ruby. 

See the readme and http://opalrb.org for more info.
